
import bdp.GestiuneTranzactii;
import bdp.MyConnection;
import static com.sun.xml.internal.fastinfoset.alphabet.BuiltInRestrictedAlphabets.table;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.UIManager.getString;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Senpai
 */
public class HOME_Jframe extends javax.swing.JFrame {

    /**
     * Creates new form HOME_Jframe
     */
//    GestiuneTranzactii trz = new GestiuneTranzactii();
    
    public HOME_Jframe() {
        initComponents();
//        show_Tranzactii();
//        trz.AdaugaTranzactie(jTable1,"");
    }
//    public ArrayList<Tranzactii>tranzlist(){
//        ArrayList<Tranzactii>tranzList = new ArrayList<>();
//        Connection con = MyConnection.getConnection();
//    PreparedStatement ps;
//    try{
//        ps=con.prepareStatement("SELECT * FROM tranzactii");       
//        
//        ResultSet rs = ps.executeQuery();
//        Tranzactii Tranzactii;
//        while(rs.next()){
//        Tranzactii=new Tranzactii(rs.getString("nume"),rs.getString("prenume"),rs.getInt("cnp"),rs.getString("valprim"),rs.getInt("sumaprim"),rs.getString("valof"),rs.getInt("sumaof"),rs.getInt("castig"),rs.getInt("nrangajat"));
//        tranzList.add(Tranzactii);
//        }
        
//        Object[] row;
//        
//        while(rs.next()){
//            row = new Object[8];
//            row[0] = rs.getInt(1);
//            row[1] = rs.getString(2);
//            row[2] = rs.getString(3);
//            row[3] = rs.getInt(4);
//            row[4] = rs.getString(5);
//            row[5] = rs.getInt(6);
//            row[6] = rs.getString(7);
//            row[7] = rs.getInt(8);        
//        }
                
//    } catch (SQLException e) {
//        JOptionPane.showMessageDialog(null, e);
//    }
//    return tranzList;
//    
//    
//    }
//    public void show_Tranzactii(){
//        ArrayList<Tranzactii> list = tranzlist();
//        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
//        Object[] row = new Object[9];
//        for(int i=0;i<=list.size();i++){
//            row[0]=list.append(i).getnume();
//            row[1]=list.append(i).getprenume();
//            row[2]=list.append(i).getcnp();
//            row[3]=list.append(i).getvalprim();
//            row[4]=list.append(i).getsumaprim();
//            row[5]=list.append(i).getvalof();
//            row[6]=list.append(i).getsumaof();
//            row[7]=list.append(i).getcastig();
//            row[8]=list.append(i).getnrangajat();
//            model.addRow(row);
//            
//    }
//        
//    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JLabelClose = new javax.swing.JLabel();
        jLabelMin = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButtonRemoveTransaction = new javax.swing.JButton();
        jButtonAddTransaction = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonRefreshTransaction = new javax.swing.JButton();
        jButtonAddClient = new javax.swing.JButton();
        jButtonRemoveClient = new javax.swing.JButton();
        jButtonRefreshClients = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(240, 52, 52));

        JLabelClose.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JLabelClose.setText("X");
        JLabelClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLabelCloseMouseClicked(evt);
            }
        });

        jLabelMin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelMin.setText("-");
        jLabelMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelMin)
                .addGap(18, 18, 18)
                .addComponent(JLabelClose)
                .addGap(44, 44, 44))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabelMin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JLabelClose, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(46, 49, 49));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nume", "Prenume", "CNP", "Val. Prim.", "Suma Prim.", "Val. Of.", "Suma Of.", "Castig", "Nr.Angajat"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nr.Client", "Nume ", "Prenume ", "CNP", "Serie/Nr Buletin"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jButtonRemoveTransaction.setBackground(new java.awt.Color(240, 52, 52));
        jButtonRemoveTransaction.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonRemoveTransaction.setText("Sterge");
        jButtonRemoveTransaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveTransactionActionPerformed(evt);
            }
        });

        jButtonAddTransaction.setBackground(new java.awt.Color(240, 52, 52));
        jButtonAddTransaction.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonAddTransaction.setText("Adauga");
        jButtonAddTransaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddTransactionActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(243, 241, 239));
        jLabel2.setText("Gestionarea tranzactiilor");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(243, 241, 239));
        jLabel3.setText("Gestionarea Clientilor");

        jButtonRefreshTransaction.setBackground(new java.awt.Color(240, 52, 52));
        jButtonRefreshTransaction.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonRefreshTransaction.setText("Tranzactii");
        jButtonRefreshTransaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefreshTransactionActionPerformed(evt);
            }
        });

        jButtonAddClient.setBackground(new java.awt.Color(240, 52, 52));
        jButtonAddClient.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonAddClient.setText("Adauga");
        jButtonAddClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddClientActionPerformed(evt);
            }
        });

        jButtonRemoveClient.setBackground(new java.awt.Color(240, 52, 52));
        jButtonRemoveClient.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonRemoveClient.setText("Sterge");
        jButtonRemoveClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveClientActionPerformed(evt);
            }
        });

        jButtonRefreshClients.setBackground(new java.awt.Color(240, 52, 52));
        jButtonRefreshClients.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonRefreshClients.setText("Clienti");
        jButtonRefreshClients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefreshClientsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButtonAddTransaction, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonRemoveTransaction, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonRefreshTransaction, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButtonAddClient, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonRemoveClient, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonRefreshClients, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(57, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonAddTransaction, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonRemoveTransaction, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonRefreshTransaction, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAddClient, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonRemoveClient, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonRefreshClients, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void JLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLabelCloseMouseClicked

        System.exit(0);
    }//GEN-LAST:event_JLabelCloseMouseClicked

    private void jLabelMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinMouseClicked

       // this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinMouseClicked

    private void jButtonAddTransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddTransactionActionPerformed
        AddTransaction AddTr = new AddTransaction();
        AddTr.setVisible(true);
        AddTr.pack();
        AddTr.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButtonAddTransactionActionPerformed

    private void jButtonRemoveTransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveTransactionActionPerformed
//        int row = jTable1.getSelectedRow();
//        String cell = jTable1.getModel().getValueAt(row, 0).toString();
//        String sql ="DELETE FROM 'tranzactii' where 'Nr. Tranzactie' = " + cell;
        try{
            int row = jTable1.getSelectedRow();
            String cell = jTable1.getModel().getValueAt(row, 0).toString();
            String sql ="DELETE FROM tranzactii where Id = " + cell;
            System.out.println(sql);
            Connection con=MyConnection.getConnection();
            PreparedStatement ps = con.prepareStatement(sql);
          //  ResultSet rs=ps.executeQuery();          
            ps.executeUpdate();
            DefaultTableModel tm = (DefaultTableModel)jTable1.getModel();            
            JOptionPane.showMessageDialog(null,"Stergere reusita");            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            
        }
        
    }//GEN-LAST:event_jButtonRemoveTransactionActionPerformed

    private void jButtonRefreshTransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshTransactionActionPerformed
       try{
           Connection con=MyConnection.getConnection();
           PreparedStatement ps = con.prepareStatement("select * from tranzactii");
           ResultSet rs = ps.executeQuery();
           DefaultTableModel tm = (DefaultTableModel)jTable1.getModel();
           tm.setRowCount(0);
           while(rs.next()){
             Object o[]={rs.getInt("Id"),rs.getString("Nume Client"),rs.getString("Prenume Client"),rs.getString("CNP Client"),rs.getString("Valuta primita"),rs.getInt("Suma primita"),rs.getString("Valuta oferita"),rs.getInt("Suma oferita"),rs.getInt("Castig"),rs.getInt("Nr. Angajat")};
             tm.addRow(o);
           
           }
       } catch (SQLException ex) {
           Logger.getLogger(HOME_Jframe.class.getName()).log(Level.SEVERE, null, ex);
       }
    }//GEN-LAST:event_jButtonRefreshTransactionActionPerformed

    private void jButtonAddClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddClientActionPerformed
        AddClient AddCl = new AddClient();
        AddCl.setVisible(true);
        AddCl.pack();
        AddCl.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButtonAddClientActionPerformed

    private void jButtonRemoveClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveClientActionPerformed
        try{
            int row = jTable2.getSelectedRow();
            String cell = jTable2.getModel().getValueAt(row, 0).toString();
            String sql ="DELETE FROM clienti where Idclient = " + cell;
            System.out.println(sql);
            Connection con=MyConnection.getConnection();
            PreparedStatement ps = con.prepareStatement(sql);
          //  ResultSet rs=ps.executeQuery();          
            ps.executeUpdate();
            DefaultTableModel tm = (DefaultTableModel)jTable1.getModel();            
            JOptionPane.showMessageDialog(null,"Stergere reusita");            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            
        }
    }//GEN-LAST:event_jButtonRemoveClientActionPerformed

    private void jButtonRefreshClientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshClientsActionPerformed
       try{
           Connection con=MyConnection.getConnection();
           PreparedStatement ps = con.prepareStatement("select * from clienti");
           ResultSet rs = ps.executeQuery();
           DefaultTableModel tm = (DefaultTableModel)jTable2.getModel();
           tm.setRowCount(0);
           while(rs.next()){
             Object o[]={rs.getInt("Idclient"),rs.getString("Nume Client"),rs.getString("Prenume Client"),rs.getString("CNP Client"),rs.getString("Serie/Nr Buletin")};
             tm.addRow(o);
           
           }
       } catch (SQLException ex) {
           Logger.getLogger(HOME_Jframe.class.getName()).log(Level.SEVERE, null, ex);
       }
    }//GEN-LAST:event_jButtonRefreshClientsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HOME_Jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HOME_Jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HOME_Jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HOME_Jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HOME_Jframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabelClose;
    private javax.swing.JButton jButtonAddClient;
    private javax.swing.JButton jButtonAddTransaction;
    private javax.swing.JButton jButtonRefreshClients;
    private javax.swing.JButton jButtonRefreshTransaction;
    private javax.swing.JButton jButtonRemoveClient;
    private javax.swing.JButton jButtonRemoveTransaction;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelMin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
